### ISSUE TITLE
can't download video

### ISSUE THREAD

**Issue by LittleTerry** [meetsohail/pexels-api-py#1]
I ran: 

search_videos = pexel.search_videos(query='health', orientation='Horizontal', size='', color='', locale='', page=1, per_page=15)
print(search_videos)

and it gave me:

![image](https://user-images.githubusercontent.com/19617725/152185535-b56e6709-c1c9-484f-8a38-4ae68b43f30b.png)

then I ran
    get_video = pexel.get_video(3209148)

it said:
![image](https://user-images.githubusercontent.com/19617725/152187070-8bfce638-7348-4bda-96e6-ffedde5b5d1e.png)

**Comment by meetsohail** [comment]
Hi [LittleTerry](https://github.com/LittleTerry), 

Thank you for pointing it out, There was an error and now I have fixed it. Now you will have no issue.

<img width="1439" alt="Screenshot 2022-02-07 at 3 49 31 PM" src="https://user-images.githubusercontent.com/5951985/152774534-f18a5a65-f163-40f1-a1c3-a42dce5fd586.png">

Thanks
